# Generated by Django 5.1.6 on 2025-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
