# Generated by Django 5.1.6 on 2025-02-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
